server:
  port: 8093
spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true
    user:
      name: zpc
      password: 123456
eureka:
  instance:
    hostname: server2
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server1:8092/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000