server:
  port: 8091 #服务端口
spring:
  application:
    name: config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: git@github.com:sddking/spring-cloud-cluster.git
          search-paths: common/config		        #配置文件目录地址
          username: sddking	    #github账号（公有项目不需要设置）
          password: Qwe!3201312	#github账号（公有项目不需要设置）
          basedir: D:\IDEALProject\spring-cloud-cluster
      label: master	#分支名称
  rabbitmq: #RabbitMQ相关的配置
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://zpc:123456@server1:8092/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}###${server.port} #指定实例id
management:
  endpoints:
    web:
      exposure:
        include: "*"